name: Update Go version

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch: {}

jobs:
  update-go-version:
    permissions:
      contents: write
      pull-requests: write
    uses: capnspacehook/go-workflows/.github/workflows/update-go-version.yml@master
